instrumentation:
    excludes:
        - ".vscode/*"
        - "config/*"
        - "media/*"
        - "resources/*"
        - ".vscodeignore"
        - "*.json"
        - "icon.png"
        - "*.txt"
        - "README.md"

check:
    global:
        statements: 91.78
        branches: 96.15
        functions: 90.79
        lines: 95.6
