instrumentation:
    excludes:
        - ".vscode/*"
        - "config/*"
        - "media/*"
        - "resources/*"
        - ".vscodeignore"
        - "*.json"
        - "icon.png"
        - "*.txt"
        - "README.md"
        - "integrationTest/*"

check:
    global:
        statements: 92.29
        branches: 96.41
        functions: 91.72
        lines: 96.01
