instrumentation:
    excludes:
        - ".vscode/*"
        - "config/*"
        - "media/*"
        - "resources/*"
        - ".vscodeignore"
        - "*.json"
        - "icon.png"
        - "*.txt"
        - "README.md"

check:
    global:
        statements: 91.39
        branches: 95.09
        functions: 89.6
        lines: 95.15
