instrumentation:
    excludes:
        - ".vscode/*"
        - "config/*"
        - "media/*"
        - "resources/*"
        - ".vscodeignore"
        - "*.json"
        - "icon.png"
        - "*.txt"
        - "README.md"

check:
    global:
        statements: 91.22
        branches: 94.97
        functions: 89.52
        lines: 95.11
