instrumentation:
    excludes:
        - ".vscode/*"
        - "config/*"
        - "media/*"
        - "resources/*"
        - ".vscodeignore"
        - "*.json"
        - "icon.png"
        - "*.txt"
        - "README.md"
        - "integrationTest/*"

check:
    global:
        statements: 93.52
        branches: 97.21
        functions: 94.02
        lines: 97.03
