sudo: false
os:
  - linux

matrix:
    include:
        - env: TASK=systest
        - env: TASK=unit

before_install:
     - if [ $TRAVIS_OS_NAME == "linux" ]; then
         sudo add-apt-repository ppa:ubuntu-toolchain-r/test
         sudo apt-get update
         sudo apt-get install gcc-4.9 g++-4.9
         sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
         export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
         sh -e /etc/init.d/xvfb start;
         sleep 3;
        fi
     - npm install -g yo
     - npm install -g generator-fabric
install: |
     - cd ./client
     - npm install
     - npm run compile
script: |
     - cd ./client

     - if [ "${TASK}" == "systest" ]; then
        ./integrationTest/scripts/run-integration-tests.sh
     else
        node ./node_modules/.bin/electron-rebuild -v 2.0

        - if [ $TRAVIS_OS_NAME == "linux" ]; then
          rm -rf ./node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc
          mv ./node_modules/grpc/src/node/extension_binary/electron-v2.0-linux-x64-glibc ./node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc
        else
          rm -rf ./node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown
          mv ./node_modules/grpc/src/node/extension_binary/electron-v2.0-darwin-x64-unknown ./node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown
        fi

        #update package json so that the tests work
        - node ../.travis/rewritePackageJson.js

        - npm test
    fi
#deploy:
#     provider: script
#     script: ./.travis/deploy.sh
#     skip_cleanup: true
#     on:
#       all_branches: true
cache: false
